### ISSUE TITLE
ClassNotFoundException: Cannot find class "oracle.jdbc.OracleDriver"/"oracle.jdbc.driver.OracleDriver"

### ISSUE THREAD

**Issue by svscorp** [mybatis/migrations#83]
I am using mybatis-migrations 3.1.1 (3.3.1 same behavior) and have followed installation instructions. I am using Oracle DB and trying to use ojdbc7 (or 8) driver to connect to my database. I have JDK8 installed

````
java version "1.8.0_102"
````

ls -la:
````
svscorp@vm:~/mybatis$ pwd
/home/svscorp/mybatis
svscorp@vm:~/mybatis$ ls -la
drwxr-xr-x 8 svscorp svscorp 4096 Oct  4 16:59 .
drwxr-xr-x 8 svscorp svscorp 4096 Oct  4 16:50 ..
drwxr-xr-x 2 svscorp svscorp 4096 May  2 00:35 bin
drwxr-xr-x 2 svscorp svscorp 4096 Oct  4 16:54 drivers
drwxr-xr-x 2 svscorp svscorp 4096 Oct  4 16:50 environments
drwxr-xr-x 2 svscorp svscorp 4096 Oct  4 16:55 lib
-rw-rw-rw- 1 svscorp svscorp 11358 Apr 25  2016 LICENSE
-rw-rw-rw- 1 svscorp svscorp 2599 Apr 25  2016 NOTICE
-rw-rw-rw- 1 svscorp svscorp 3042 Apr 25  2016 README.md
drwxr-xr-x 2 svscorp svscorp 4096 Oct  4 16:59 scripts
````

more info on ENV VARS
````
svscorp@vm:~/mybatis$ echo $MIGRATIONS
/home/svscorp/mybatis/bin
svscorp@vm:~/mybatis$ echo $MIGRATIONS_HOME
/home/svscorp/mybatis
svscorp@vm:~/mybatis$ echo $PATH
/home/svscorp/mybatis/bin:<other-stuff>
````

development.properties
````
time_zone=GMT+0:00
driver="oracle.jdbc.OracleDriver"
url="jdbc:oracle:thin:@//[IP]:[PORT]/[DB]"
username=[USERNAME]
password=[USERNAME]
full_line_delimiter=false
auto_commit=false
````

In the drivers I have ojdbc8.jar (tried with ojdbc7.jar - same result).

Error message (--trace):
````
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
------------------------------------------------------------------------
-- MyBatis Migrations - status
------------------------------------------------------------------------
ID             Applied At          Description
================================================================================
------------------------------------------------------------------------
-- MyBatis Migrations FAILURE
-- Total time: 0s
-- Finished at: Wed Oct 04 17:04:15 CEST 2017
-- Final Memory: 10M/483M
------------------------------------------------------------------------

ERROR: Could not create SqlRunner. Cause: java.sql.SQLException: Error setting driver on UnpooledDataSource. Cause: java.lang.ClassNotFoundException: Cannot find class: "oracle.jdbc.OracleDriver"org.apache.ibatis.migration.MigrationException: Could not create SqlRunner. Cause: java.sql.SQLException: Error setting driver on UnpooledDataSource. Cause: java.lang.ClassNotFoundException: Cannot find class: "oracle.jdbc.OracleDriver"
        at org.apache.ibatis.migration.operations.DatabaseOperation.getSqlRunner(DatabaseOperation.java:88)
        at org.apache.ibatis.migration.operations.DatabaseOperation.changelogExists(DatabaseOperation.java:73)
        at org.apache.ibatis.migration.operations.StatusOperation.operate(StatusOperation.java:44)
        at org.apache.ibatis.migration.commands.StatusCommand.execute(StatusCommand.java:30)
        at org.apache.ibatis.migration.CommandLine.runCommand(CommandLine.java:65)
        at org.apache.ibatis.migration.CommandLine.execute(CommandLine.java:42)
        at org.apache.ibatis.migration.Migrator.main(Migrator.java:20)
Caused by: java.sql.SQLException: Error setting driver on UnpooledDataSource. Cause: java.lang.ClassNotFoundException: Cannot find class: "oracle.jdbc.OracleDriver"
        at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.initializeDriver(UnpooledDataSource.java:221)
        at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:200)
        at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:196)
        at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.getConnection(UnpooledDataSource.java:93)
        at org.apache.ibatis.migration.DataSourceConnectionProvider.getConnection(DataSourceConnectionProvider.java:34)
        at org.apache.ibatis.migration.operations.DatabaseOperation.getSqlRunner(DatabaseOperation.java:86)
        ... 6 more
````

**Same goes if I try older format specifying the driver: oracle.jdbc.driver.OracleDriver**

Where did it go wrong?

**Comment by harawata** [comment]
The driver class should be `oracle.jdbc.driver.OracleDriver`.

**Comment by svscorp** [comment]
I wouldn't close the thread, because I tried both: oracle.jdbc.driver.OracleDriver and oracle.jdbc.OracleDriver

"oracle.jdbc.driver.OracleDriver" - the old format

**Comment by svscorp** [comment]
@h3adache please, reopen the issue. it is not solved.

**Comment by harawata** [comment]
OK, I'll reopen.

That error occurs when the program cannot find/read the driver JAR or the class is not in the JAR file.
A few things you can try:

1. Check the content of the JAR archive and make sure the `OracleDriver` class is actually included.
1. Test with another database like HSQLDB and see if it fails with the same exception.

**Comment by h3adache** [comment]
Is your driver in the driver folder?
What do you see when you execute
`jar -tvf ./driver/ojdbc8.jar`

**Comment by svscorp** [comment]
Hi @h3adache 

````
jar -tvf ./drivers/ojdbc8.jar | grep oracledriver -i
  2604 Tue Dec 13 08:39:48 CET 2016 oracle/jdbc/OracleDriver.class
   456 Tue Dec 13 08:39:48 CET 2016 oracle/jdbc/driver/OracleDriver$1.class
   836 Tue Dec 13 08:39:48 CET 2016 oracle/jdbc/driver/OracleDriver$2.class
 19098 Tue Dec 13 08:39:48 CET 2016 oracle/jdbc/driver/OracleDriver.class
  1203 Tue Dec 13 08:39:48 CET 2016 oracle/jdbc/driver/OracleDriverExtension.class
````

**Comment by harawata** [comment]
Please try the latest version 3.3.1.
If it still does not work, try it with HSQLDB and let us know the result.

**Comment by svscorp** [comment]
Hi @harawata, honestly it is initially the case (corrected in description). I'll try with another DB and tell the result.

**Comment by h3adache** [comment]
hi @svscorp I reproduced your issue
Please change your development.properties to:
```
driver=oracle.jdbc.OracleDriver
url=jdbc:oracle:thin:@//[IP]:[PORT]/[DB]
```
As you see the only difference is that I removed the quotations from your driver and url.
Properties files are read verbatim, they do not use quotation marks.

**Comment by svscorp** [comment]
I'll try @h3adache , thank you.

**Comment by svscorp** [comment]
@h3adache that's a nice catch.

Thank you. Can be closed.
